from position import Position

# Constants for sizing
CARD_SCALE = 0.6

# How big are the cards?
CARD_WIDTH = 140 * CARD_SCALE
CARD_HEIGHT = 190 * CARD_SCALE

# Screen title and size
SCREEN_WIDTH = 1024
# Monitor height
# SCREEN_HEIGHT = 768

# Laptop height
SCREEN_HEIGHT = 600

SCREEN_TITLE = "Hearts"

PADDING_OFFSET = 0.25
PADDING_OFFSET = 0.25
# Card positioning for user and north i.e. rows
X_SPACING = 50
HORIZONTAL_OVERLAP = CARD_WIDTH-X_SPACING
ROW_WIDTH = 12*(CARD_WIDTH-HORIZONTAL_OVERLAP)+CARD_WIDTH
LEFT_PAD = (SCREEN_WIDTH-ROW_WIDTH)/2  
USER_POSITION = Position(
    x_pos=LEFT_PAD + CARD_WIDTH/2,
    y_pos=CARD_HEIGHT/2+CARD_HEIGHT*PADDING_OFFSET
)
NORTH_POSITION = Position(
    x_pos=LEFT_PAD + CARD_WIDTH/2,
    y_pos=SCREEN_HEIGHT-(CARD_HEIGHT/2)-(CARD_HEIGHT*PADDING_OFFSET)
)
# Card positioning for east and west i.e. columns
Y_SPACING = 30
VERTICAL_OVERLAP = CARD_HEIGHT-Y_SPACING
COLUMN_HEIGHT = 12*(CARD_HEIGHT-VERTICAL_OVERLAP)+CARD_HEIGHT
TOP_PAD = (SCREEN_HEIGHT-COLUMN_HEIGHT)/2
EAST_POSITION = Position(
    x_pos=SCREEN_WIDTH-CARD_WIDTH/2-CARD_WIDTH*PADDING_OFFSET  ,
    y_pos=SCREEN_HEIGHT-CARD_HEIGHT/2 - TOP_PAD
)
WEST_POSITION = Position(
    x_pos=CARD_WIDTH/2+CARD_WIDTH*PADDING_OFFSET,
    y_pos=SCREEN_HEIGHT-CARD_HEIGHT/2 - TOP_PAD
)