from constants.screen import *

TRICK_VERTICAL_OVERLAP = 0.8
TRICK_VERTICAL_OFFSET = (CARD_HEIGHT/2)*TRICK_VERTICAL_OVERLAP

TRICK_HORIZONTAL_OVERLAP = 0.95
TRICK_HORIZONTAL_OFFSET = CARD_WIDTH*TRICK_HORIZONTAL_OVERLAP